### ISSUE TITLE
Support analyzing specific repositories

### ISSUE THREAD

**Issue by hicksjacobp** [mona-actions/gh-repo-stats#27]
While scanning an entire organization is nice, it can be quite painful when an organization has hundreds of repositories. My organization is migrating in chunks, so we would like to do analysis only on specific repositories when we're ready to migrate them.

Perhaps add a new parameter for a list of repositories and/or a new parameter for a file of listed repositories (or enhance the logic around the `input` parameter to recognize repositories)?

I could expect that if repositories were from different organizations or if both a list of repositories and an organization was provided, then the tool could error out.

**Comment by admiralAwkbar** [comment]
This was solved in #29
