### ISSUE TITLE
Strangely that didn't happen to me.  I wonder if it was using my `GITHUB_TOKEN` that is in my environment?

### ISSUE THREAD

**Issue by Juanareyessanchez** [mona-actions/gh-repo-stats#57]
Strangely that didn't happen to me.  I wonder if it was using my `GITHUB_TOKEN` that is in my environment?
Anyhow, could `gh auth` allow this to use a github app for authentication so we get 15k requests per hour?
Is the `gh` tool even the right spot to make that request?

_Originally posted by @Chocrates in https://github.com/mona-actions/gh-repo-stats/issues/26#issuecomment-1144178823_

**Comment by pmartindev** [comment]
This extension doesn't currently utilize `gh auth`, but you can use a tool such as https://github.com/link-/gh-token to generate a short lived token (1 hour) GH app token to pass in.
