### ISSUE TITLE
gh: Field 'discussions' doesn't exist on type 'Repository'

### ISSUE THREAD

**Issue by ju2wheels** [mona-actions/gh-repo-stats#75]
Im trying to use against GHE server 2.22:

```
 gh repo-stats -H company_ghe_server --org company_org

######################################################
######################################################
############# GitHub repo list and sizer #############
######################################################
######################################################

GitHub Enterprise Server v2.22.24
------------------------------------------------------
Getting repositories for org: company_org
gh: Rate limiting is not enabled. (HTTP 404)
API rate limiting is not enabled.
gh: Field 'discussions' doesn't exist on type 'Repository'
Error getting Repos for Org: company_org
--repo-page-size might need to be set to a lower value

######################################################
The script has completed

Results file:[company_org-all_repos-202311101323.csv]
######################################################
****
```

**Comment by 3nassale7** [comment]
> Im trying to use against GHE server 2.22:
> 
> ```
>  gh repo-stats -H company_ghe_server --org company_org
> 
> ######################################################
> ######################################################
> ############# GitHub repo list and sizer #############
> ######################################################
> ######################################################
> 
> GitHub Enterprise Server v2.22.24
> ------------------------------------------------------
> Getting repositories for org: company_org
> gh: Rate limiting is not enabled. (HTTP 404)
> API rate limiting is not enabled.
> gh: Field 'discussions' doesn't exist on type 'Repository'
> Error getting Repos for Org: company_org
> --repo-page-size might need to be set to a lower value
> 
> ######################################################
> The script has completed
> 
> Results file:[company_org-all_repos-202311101323.csv]
> ######################################################
> ****
> ```

S
